### ISSUE TITLE
Facebook page id typoscript

### ISSUE THREAD

**Issue by bullshit** [dcngmbh/moox_social#2]
Hello guys,

i think you have forgotten to add the "api_page_id" option to typoscript constants
https://github.com/dcngmbh/moox_social/blob/master/Configuration/TypoScript/constants.txt#L19-L22

```typoscript
# cat=plugin.tx_mooxsocial/content/12; type=string; label= [Facebook][API] Page ID(s)
api_page_id =
```
and at https://github.com/dcngmbh/moox_social/blob/master/Configuration/TypoScript/setup.txt#L17-L18
```typoscript
api_page_id = {$plugin.tx_mooxsocial.settings.api_page_id}
```
Is that right?

Regards

**Comment by adrolli** [comment]
You need to set the API page ID in the MOOX Social content element if you use the direkt API call. Using the cached mode of MOOX Social, add it to your task within TYPO3 task planner. If you need to call a MOOX Social stream by Fluid, include the API page ID into your code. We did it this way instead of using a TS constant, because of flexibility. You may connect more than one page within the same root page setup.

**Comment by bullshit** [comment]
thank you for your explaination
